### ISSUE TITLE
🐛 Bug: UI issue in active navigation link in dark mode

### ISSUE THREAD

**Issue by StyleShit** [LearningTypeScript/site#127]
### Bug Report Checklist

- [X] I have [searched for related issues](https://github.com/LearningTypeScript/site/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.
- [X] This is the appropriate issue form for the bug I would like to report.

### Expected

The link should be properly visible with good color contrast

### Actual

Black-colored text on a dark background isn't that readable

<img width="567" alt="image" src="https://github.com/LearningTypeScript/site/assets/32631382/ab27a026-3230-45db-bab4-8615639ff860">

Accessibility dev tools (on Firefox):

<img width="388" alt="image" src="https://github.com/LearningTypeScript/site/assets/32631382/1b28c714-ba1d-47a4-ba92-5e1984e0a9fa">

Seems fine in light mode though:

<img width="564" alt="image" src="https://github.com/LearningTypeScript/site/assets/32631382/43e0456e-57ad-4496-bc5f-6e8ad894fd68">

**Comment by JoshuaKGoldberg** [comment]
👍 definitely a bug - thanks for reporting!
