### ISSUE TITLE
🐛 Bug: "Edit this page" links are broken in projects

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [LearningTypeScript/site#38]
### Bug Report Checklist

- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.
- [X] This is the appropriate issue form for the bug I would like to report.

### Expected

In pages like https://www.learningtypescript.com/from-javascript-to-typescript, _Edit this page_ takes you to URLs like https://github.com/LearningTypeScript/projects/tree/main/src/content/external/projects/from-javascript-to-typescript/README.md. That's a 404.

### Actual

They should go cross-repo to URLs like https://github.com/LearningTypeScript/projects/blob/main/projects/from-javascript-to-typescript/README.md.

**Comment by ssavi-ict** [comment]
HI @JoshuaKGoldberg, I understand your requirement. 
I explored this repository and the _projects_ repository. However, I failed to figure out the place where I can change the link of "Edit this page". 
Can you help me out here?

**Comment by JoshuaKGoldberg** [comment]
🎉 Great, thanks for taking a look!

Much of the site's UI is configured in the `docusaurus.config.js` file in the root directory. It's documented here: https://docusaurus.io/docs/configuration & https://docusaurus.io/docs/api/docusaurus-config.

Does that help?

**Comment by ssavi-ict** [comment]
@JoshuaKGoldberg, Thanks it helped. 
I created a PR. Please review it and feel free to notify any up-gradation.
